FROM golang:1.14.3-alpine3.11 as builder
RUN apk add git
RUN git clone https://github.com/concourse/registry-image-resource.git /src/registry-image-resource
WORKDIR /src/registry-image-resource
ENV CGO_ENABLED 0
RUN go get -d ./...
RUN go build -o /assets/in ./cmd/in
RUN go build -o /assets/out ./cmd/out
RUN go build -o /assets/check ./cmd/check

FROM alpine:edge AS resource
RUN apk add --no-cache bash tzdata ca-certificates unzip zip gzip tar
COPY --from=builder assets/ /opt/resource/
RUN chmod +x /opt/resource/*

FROM resource
WORKDIR /go/registry-image-resource

